#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: 8080
  servlet:
    context-path: /bank

spring:
  datasource:
    url: jdbc:postgresql://bank-database:5432/bank_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

logging:
  level:
    liquibase: debug

jwt:
  secret: 12345678901234567890123456789012
  expiration: 86400000
